version: "3.3"
services:
  jenkins:
    image: myjenkins:1.0.0
    container_name: jenkins
    user: root
    restart: always
    privileged: true
    ports:
      - 18080:8080
      - 50000:50000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/:/var/jenkins_home/
      #- /usr/bin/docker:/usr/bin/docker
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /etc/docker/daemon.json:/etc/docker/daemon.json
